apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine3.19
        ports:
        - containerPort: 5432
        env:
        - name: TZ
          value: "Asia/Jakarta"
        - name: PGTZ
          value: "Asia/Jakarta"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "Password09"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}