apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-app-green
  namespace: space
  labels:
    app: space-app
    version: v7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-app
      version: v7
  template:
    metadata:
      labels:
        app: space-app
        version: v7
    spec:
      containers:
      - name: space-app
        image: pro24/space:v7
        ports:
        - containerPort: 8080
        env:
          - name: VERSION
            value: "GREEN"
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "400Mi"