apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: space
spec:
  selector:
    app: kong
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
  - name: proxy-ssl
    port: 8443
    targetPort: 8443
  type: ClusterIP